/*
    This file was generated automatically by Alchitry Labs 2.0.28-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module x_bitshiftleft #(
        parameter SHIFT = 4'h8
    ) (
        input wire [31:0] a,
        input wire shift,
        input wire pad,
        output reg [31:0] out
    );
    logic [4:0] R_19b51a0b_i;
    logic [5:0] RR_19b51a0b_i;
    logic [31:0] M_mux_2_32_s0;
    logic [31:0][1:0] M_mux_2_32_in;
    logic [31:0] M_mux_2_32_out;
    
    genvar idx_0_1949749938;
    
    generate
        for (idx_0_1949749938 = 0; idx_0_1949749938 < 32; idx_0_1949749938 = idx_0_1949749938 + 1) begin: forLoop_idx_0_1949749938
            mux_2 mux_2_32 (
                .s0(M_mux_2_32_s0[idx_0_1949749938]),
                .in(M_mux_2_32_in[idx_0_1949749938]),
                .out(M_mux_2_32_out[idx_0_1949749938])
            );
        end
    endgenerate
    
    
    logic [31:0] shifted_bits;
    always @* begin
        shifted_bits = {a[5'h1f - SHIFT:1'h0], {SHIFT{pad}}};
        M_mux_2_32_in = {{2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0}};
        M_mux_2_32_s0 = {6'h20{shift}};
        for (RR_19b51a0b_i = 0; RR_19b51a0b_i < 6'h20; RR_19b51a0b_i = RR_19b51a0b_i + 1) begin
      R_19b51a0b_i = (0) + RR_19b51a0b_i * (1);
            M_mux_2_32_in[R_19b51a0b_i][1'h0] = a[R_19b51a0b_i];
            M_mux_2_32_in[R_19b51a0b_i][1'h1] = shifted_bits[R_19b51a0b_i];
        end
        out = M_mux_2_32_out;
    end
    
    
endmodule